type: {{serviceType}}
description: {{description}}
author: {{author}}

startup:
  command: node src/server.js
  online-text: online at port
tests: bin/test

messages:
  receives:
    - ping
  sends:
    - pong

dependencies:
