type: {{serviceType}}
description: {{description}}
author: {{author}}

startup:
  command: node src/server.js
  online-text: online at port

messages:
  receives:
    - ping
  sends:
    - pong

development:
  scripts:
    start: node src/server.js
    test: bin/test
  dependencies:
